<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ZhuJieJing.Assets\ZhuJieJing.Assets.csproj" />
    <ProjectReference Include="..\ZhuJieJing.Core\ZhuJieJing.Core.csproj" />
    <ProjectReference Include="..\ZhuJieJing.Minecraft\ZhuJieJing.Minecraft.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\VoxelPreview.hlsl"
                      LogicalName="ZhuJieJing.Renderer.Assets.VoxelPreview.hlsl" />
    <EmbeddedResource Include="Assets\StaticSky.png" LogicalName="ZhuJieJing.Renderer.Assets.StaticSky.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
    <PackageReference Include="Vortice.Wpf" Version="3.8.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
